### PR TITLE
Upgrade to strong-swagger-ui@21.0 (swagger-ui@2.1)

### PR DESCRIPTION
**Pull request by bajtos**
This patch upgrades loopback-explorer to use strong-swagger-ui@21.0, which is based on swagger-ui@2.1 and supports Swagger Spec 2.0.

**Notes**

 - strong-swagger-ui@21.0 does not implement all customizations from v20.0 yet, I'll be working on that in follow-up pull requests.

 - For endpoints `GET /models`, the response model is not correctly rendered ATM. I suspect this is caused by #111 and/or #113, I'll be investigating the problem after this PR is landed.

Connect to strongloop-internal/scrum-loopback#412
Connect to strongloop/loopback-explorer#54

/to @raymondfeng @STRML please review

### CODE REVIEW

**Comment by bajtos** [comment]
@slnode test please

File: public/lib/loadSwaggerUI.js [hunk 1]
```diff
@@ -16,12 +21,27 @@ $(function() {
       apiKey: '',
       dom_id: 'swagger-ui-container',
       supportHeaderParams: true,
-      supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
+      supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
```
Comment (raymondfeng) [inline public/lib/loadSwaggerUI.js]: What about `head`?

Comment (bajtos) [inline public/lib/loadSwaggerUI.js]: AFAICT, the flag "supportedSubmitMethods" controls whether operation's model is editable or readonly.

https://github.com/strongloop/strong-swagger-ui/blob/b92b67923612d0f855ebe2c46ffd8ca728500fd2/src/main/javascript/view/OperationView.js#L80-L83

By default, this array is set to all HTTP verbs:

https://github.com/strongloop/strong-swagger-ui/blob/b92b67923612d0f855ebe2c46ffd8ca728500fd2/src/main/javascript/SwaggerUi.js#L26-L36

To be honest, I don't completely understand the purpose of this option. I just applied the value from swagger-ui's index.html. Perhaps we can remove this line completely and use swagger-ui's default instead?

**Comment by bajtos** [comment]
I have removed `supportedSubmitMethods` and use the default list provided by (strong-)swagger-ui.

@raymondfeng LGTY now?

**Comment by raymondfeng** [comment]
LGTM

**Comment by bajtos** [comment]
@slnode test please
